dataset_path: {{ dataset }}

dataset:
  class: Vactivity
  path: ~/scratch/jingao/Interact/data/20230927_2k
  atom_feature: null
  bond_feature: null
  transform:
    class: ProteinView
    view: residue

transform:
  class: ProteinView
  view: residue

task:
  class: PropertyPrediction
  model:
    class: FusionNetwork
    sequence_model:
      class: ESM
      path: ~/.cache/torch/hub/checkpoints
      model: ESM-2-650M
    structure_model:
      class: GearNet
      input_dim: 1280
      hidden_dims: [512, 512, 512, 512, 512, 512]
      batch_norm: True
      concat_hidden: True
      short_cut: True
      readout: 'sum'
      num_relation: 7
      edge_input_dim: 59
      num_angle_bin: 8
  graph_construction_model:
    class: GraphConstruction
    node_layers:
      - class: AlphaCarbonNode
    edge_layers:
      - class: SequentialEdge
        max_distance: 2
      - class: SpatialEdge
        radius: 10.0
        min_distance: 5
      - class: KNNEdge
        k: 10
        min_distance: 5
    edge_feature: gearnet
  criterion: mse
  metric: ['mae', 'rmse', 'spearmanr', 'pearsonr']
  num_mlp_layer: 3
  task: "activity"

# checkpoint: {{ ckpt }}
checkpoint: /home/ubuntu/scratch/jingao/Interact/data/ckpt/model_epoch_21.pth
batch_size: 2
gpu: 0
tag: model5
start: 160000
end: 170000
